version: '3.7'
services:
    registry:
        restart: always
        image: registry:2
        container_name: my-web-container
        ports:
            - 5000:5000
            - 443:443
        environment:
            REGISTRY_HTTP_ADDR: 0.0.0.0:443
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/localhost.crt
            REGISTRY_HTTP_TLS_KEY: /certs/localhost.key
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - data/:/var/lib/registry
            - ./certs/:/certs
            - ./auth/:/auth
   ui:
        image: joxit/docker-registry-ui:static
        environment:
          - REGISTRY_TITLE=My Private Docker Registry
        volumes:
          - ./nginx/nginx.conf: /etc/nginx/conf.d/default.conf
          - ./certs/fullchain.pem: /etc/nginx/certs/fullchain.pem
          - ./certs/privkey.pem: /etc/nginx/certs/privkey.pem
        ports:
          - 80:80
          - 443:443
        depends_on:
          - registry

volumes:
  certs 
  auth 
  data 